# Site settings
title: Lawrence Woodman
author: "Lawrence Woodman"
email: lwoodman@vlifesystems.com
description: > # this means to ignore newlines until "baseurl:"
  Random things that catch my eye that don't have a natural home elsewhere.
permalink:   /blog/:year/:month/:day/:title
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lawrencewoodman.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

gems:
 - jekyll-feed
